### ISSUE TITLE
The basic info of an author's response must contain the affiliation info.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#10]
**Endpoint:**
http://apis.impactu.colav.co:8010/app/person/640f41b51c64b4bf1b57fe10

This information is already in the authors' search results so follow the same structure in this endpoint.
**Example:**
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/62b5dcbb-dfe5-4e3a-af8d-ebbe7196e2c7)
http://apis.impactu.colav.co:8010/app/search/person?limit=10&page=1&sort=citations&keywords=diego+alejandro+restrepo

**Comment by Simon3640** [comment]
affiliation info added to person schema:
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/4a9993b3-4cf3-41cd-8dfd-32855f6ffe72)
bf9ae1e548a0a85ec625c2d6ea18bdd283da6270
