### ISSUE TITLE
Error requesting some of the works.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#11]
I'm getting a TypeError with some of the works specific info:
http://apis.impactu.colav.co:8010/app/work/65f0411e46fdfdf4499c55bd?section=info

**Comment by omazapa** [comment]
I did an updated in the database, then id was changed, this is  the new url
https://apis.impactu.colav.co/app/work?section=info&id=65f97f5e8c2f558aa012ac16

**Comment by Simon3640** [comment]
new validation for source id
56576540e14e93389706414ce4f2d82ec33b247b
