### ISSUE TITLE
Error requesting search results.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#12]
I'm getting an AttributeError when requesting the search results of Institutions, faculties, departments, and groups.
Example:
http://apis.impactu.colav.co:8010/app/search/affiliations/institution?max=10&page=1&sort=citations&keywords=antioquia

**Comment by Simon3640** [comment]
dict instead dict fixed/
bed78435ad32c044df4ccf7d78bfabfa8ec27005

**Comment by luismvargasg** [comment]
Now I'm getting a TypeError:
http://apis.impactu.colav.co:8010/app/search/affiliations/department?max=10&page=1&sort=citations

**Comment by Simon3640** [comment]
sort removed until db includes citations count and procuts count.
8f58773c231e4fb659a759aa082069594dc0f06b
