### ISSUE TITLE
Abstract is missing in the works response.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#13]
The works request must contain an "abstract" variable with the text.
http://apis.impactu.colav.co:8010/app/work/65f96b868c2f558aa0114409?section=info

Example:
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/530f7fbc-e74b-4e72-b00d-9f25c808017e)

**Comment by Simon3640** [comment]
new feature added.
79e9302efc77624c4ded4d75344e225041cb9d82
