### ISSUE TITLE
NaNs are being returned in some API responses.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#14]
There are some fields in the document lists that contain NaN values, which cannot be processed by the frontend. This causes an error in the product listing component. To resolve this issue, please remove the NaN values from the response. You can replace them with empty strings.
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/02310aa5-6b7b-4d1e-b25f-fa78cb7bb8de)
http://apis.impactu.colav.co:8010//app/affiliation/faculty/65f93c022685775e89fdce51/research/products?max=10&page=9&sort=citations

**Comment by omazapa** [comment]
@fedevergara please investigate this as well

**Comment by omazapa** [comment]
this is the uptated link for the new data

http://apis.impactu.colav.co:8010//app/affiliation/faculty/65fb54583f94c992f8746f35/research/products?max=10&page=9&sort=citations

**Comment by Simon3640** [comment]
dd012f5d4baee6de2ee33a50baf6984bef44e242
its removed now from requests, in db we must to remove NaN types in works we have 466 works with NaN in source's name
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/4fe4b880-ee07-4c7a-bf83-651ee0fa3c24)

**Comment by omazapa** [comment]
There was an error in backend but it have to be fixed as well in ETL.
```
kahi> db.works.countDocuments({"source.name": NaN})
466

```

**Comment by omazapa** [comment]
fixed with https://github.com/colav/Kahi_plugins/pull/291
