### ISSUE TITLE
Repeat authors are appearing in the list of authors of some documents.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#15]
Repeated authors appear in the list with the same ID and name, which causes errors in the frontend because the component that generates the clickable list must obtain unique keys that are not repeated in the DOM.
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/9f0c9f19-0548-4ee8-a92b-cce48ed5c720)

Example of document ID with the issue: 65f977348c2f558aa0125f20

http://apis.impactu.colav.co:8010//app/affiliation/faculty/65f93c022685775e89fdce51/research/products?max=10&page=1&sort=citations

**Comment by Simon3640** [comment]
Work service was updated to be reusable
806e625d065ac27ce8d992eeace3c1b491603014
Unique authors by id
9979fc36b3496a291a5475206facd76c68bfdacd
