### ISSUE TITLE
TypeError on "products_age" plot.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#17]
I'm getting a TypeError in the "Products according to age range of the authors" plot:
http://apis.impactu.colav.co:8010//app/affiliation/institution/65fb53f83f94c992f872d3b0/research/products?plot=products_age

**Comment by Simon3640** [comment]
63c17b120b0b0d8660e7db0aab63dd38fb6fa1e7
Exception handled.
