### ISSUE TITLE
Error requesting a work

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#18]
I'm getting a KeyError:
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/36599edf-38dd-4a1c-aebe-79c0a49f51c8)

http://apis.impactu.colav.co:8010//app/work/660b5513fe99b8857e9beab1?section=info

**Comment by Simon3640** [comment]
fixed with an ternary operator
0573ee24f24127fcc5e342039a55a3f970baa534
