### ISSUE TITLE
The citation count for a product does not correspond to the information in the modal.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#2]
**Request:**
The data is being taken from different sources, the count must be normalized.

**Example:**
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/698d93b1-773c-49d9-9e7c-bda803c1b160)

**Comment by Simon3640** [comment]
El orden de las fuentes se puede ver alterado al consultarlo de manera individual, como en el anterior, siento que la mejor manera de solucionar este problema puede ser mostrar todas las fuentes, sin embargo se implementa un sort para el conteo de citaciones en el back, finalmente el conteo de citaciones vendría siempre de mayor a menor: [
                {
                    "count": 20,
                    "source": "scholar"
                },
                {
                    "count": 19,
                    "source": "openalex"
                },
                {
                    "count": 1,
                    "source": "scopus"
                },
                {
                    "count": 0,
                    "source": "wos"
                }
            ],

37d208d2712beeb60d25ca82e31fe66eb6cb222d
