### ISSUE TITLE
Wrong info in the products list of an author.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#22]
The data is empty but it says that the total_results is 1
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/b805bfba-8bf3-4382-a350-5edd2defc043)
https://dev.apis.impactu.colav.co//app/person/660b049dfe99b8857e881105/research/products?max=10&page=1&sort=citations

**Comment by luismvargasg** [comment]
Author profile: 660b049dfe99b8857e881107

**Comment by Simon3640** [comment]
No es un error directamente, es solo que al ordenar por citaciones se pierde el articulo
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/3de74ff0-17b1-4461-8fe4-4e00bb09fdbc)
Como se puede ver el artículo no tiene citaciones, sin el sort de citaciones aparece:
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/3f19b249-b1ba-46fb-bda4-847859983898)

**Comment by Simon3640** [comment]
Solución provisional, el sort debe ir como citations- es decir descendente para ordenar de mayor a menor.
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/6654d39a-6e16-448c-95f5-432888476832)
https://github.com/colav-playground/impactu-backend-service/commit/c2f94360ad2738bb606c9e48130dfd95b09814c7
