### ISSUE TITLE
The subjects tags for a product are unnamed.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#3]
**Request:**
Fix the subjects list of a product, the tags are all displayed with the name "No name in db".

**Example:**
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/b710cf60-a9ab-44ff-8864-38e4915de7dd)

**Comment by Simon3640** [comment]
This issue was corrected with db actualization.
