### ISSUE TITLE
Remove the "names" list in the affiliations of an author of a product.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#4]
**Request:**
Please remove the list because it is unnecessary

**Example:**
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/68fbda5f-4fe2-4ac1-909d-d0cce72789c0)

[URL](http://apis.impactu.colav.co:8010//app/search/works?limit=100&page=1&sort=citations&keywords=covid)

**Comment by Simon3640** [comment]
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/7ebc5cf1-7287-4240-93f4-c1dd47893633)
Issue fixed with db actualization
