### ISSUE TITLE
Fix and normalize pagination on entities profile

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#6]
**Request:**
Fix the pagination behavior and normalize the variable names, in some cases the URL must contain: "max_results" and in other endpoints such as "search" the name is "limit"; please refer to the standard that Omar built and use the same name for every single endpoint.

**Example:**
I requested the second page with 10 products from a research group and the response only send me 8 items:
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/e6d45dd2-667e-411c-9075-5ef0e5d7e71e)

For the same profile it says that there are 90 products available but it shows only 62:
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/7064f12c-8e59-43bb-b5d4-cddb288f6898)
The total_results and the count doesn't match

[URL](http://apis.impactu.colav.co:8010/app/affiliation/group/63935b6571459ce0bcb93413/research/products?max_results=10&page=2)

**Comment by omazapa** [comment]
@Simon3640 this is the standard please use it for the endpoints
https://docs.google.com/document/d/17ppS_W8I4USXdu49_OP60Cr3VP1tHnH4/edit

**Comment by Simon3640** [comment]
Fixed the standard for endpoints and the limit search in pipeline
1c6242a5df9562e1185fc1080cf8677d719dae33
