### ISSUE TITLE
Entities must return citations_count and products_count.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#7]
The response of the following entities must contain the "citations_count" and "products_count":
- Person.
- Institutions.
- Groups.
- Departments.
- Faculties.

API response example:
![image](https://github.com/colav/HunabKu_plugins/assets/60363752/cb3d5270-eb1c-4e12-8a9b-c455d4af80bd)

Frontend example:
![image](https://github.com/colav/HunabKu_plugins/assets/60363752/5eda6118-6cf3-483c-b9cc-22e6ee9da051)

**Comment by Simon3640** [comment]
pipelines added for count products and citation count response.
e4c731af1663bebd3c686610fded17829de9220c

**Comment by Simon3640** [comment]
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/f7e30dab-cbde-4245-8312-fa688777fa80)

**Comment by luismvargasg** [comment]
1. Entity "Person" is still missing this information.
2. The information for the entity "Institution" is stuck with the same number:
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/2bbc0bed-2fc5-4d81-a904-5ba9edf03563)

**Comment by Simon3640** [comment]
The server is returning diferent values for institutios as you can see in the next request:
![Captura desde 2024-03-21 23-30-59](https://github.com/colav-playground/impactu-backend-service/assets/41750812/d7f55da7-a238-4e18-8d1a-c398ab7b44fc)
Person count was added
edb7c36761fe6363bbea52d37f7f2c0f478dd18f
