### ISSUE TITLE
Normalize the response of the basic info of an entity.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#8]
**Request:**
Make a minor change in the data structure of the response of the basic info of an entity.

[URL](http://apis.impactu.colav.co:8010//app/affiliation/department/63935abf71459ce0bcb933af)

**Current Response:**
Info is coming inside of a dictionary:
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/19c16094-8b56-45de-bd0e-28994c722426)

**Required structure:**
Use instead the same structure as a list used in the search result:
![image](https://github.com/colav-playground/impactu-backend-service/assets/60363752/befccc91-adc2-4172-a09d-7e67d223d5ef)

* I think the proper name is "institution" instead of "university".

**Comment by Simon3640** [comment]
Relations are now as a list
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/081e47e2-31c3-4748-a3bc-f94d2ebf93e4)
de3d83ebb3000b720252515fa7b3ece29a9849f9
