### ISSUE TITLE
Research products on authors are not working.

### ISSUE THREAD

**Issue by luismvargasg** [colav-playground/impactu-backend-service#9]
I'm getting a KeyError on this response:

http://apis.impactu.colav.co:8010/app/person/640f41b51c64b4bf1b57fe10/research/products

**Comment by Simon3640** [comment]
![image](https://github.com/colav-playground/impactu-backend-service/assets/41750812/9e8c7a1b-09e5-43cc-8207-2c42bc17c8c7)
Working with db actualization.
